/*
This file is automatically generated
DO NOT MODIFY BY HAND
FirstPage
C Source
*/

#include "FirstPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static Esd_BitmapCell FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[9];
static const Esd_BitmapCell* FirstPage_ESD_Image_SlideShow_Array_Input__Property(void *context, size_t *size) { *size = 9; return FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array; }
static uint8_t FirstPage_ESD_Toggle_Font__Property(void *context) { return 29; }
static uint8_t FirstPage_ESD_Push_Button_Font__Property(void *context) { return 29; }
static uint8_t FirstPage_ESD_Label_Font__Property(void *context) { return 31; }
static const char * FirstPage_ESD_Label_Text__Property(void *context) { return "ESD"; }

static Ft_Esd_WidgetSlots s_FirstPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))FirstPage_End,
};


void FirstPage__Fixed_Position__Initializer(FirstPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void FirstPage__ESD_Image_SlideShow__Initializer(FirstPage *context)
{
	Ft_Esd_Image_SlideShow *object = (Ft_Esd_Image_SlideShow *)&context->ESD_Image_SlideShow;
	Ft_Esd_Image_SlideShow__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 21;
	object->Widget.LocalY = 161;
	object->Widget.LocalWidth = 282;
	object->Widget.LocalHeight = 190;
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[0] = barbecue_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[1] = chess_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[2] = diveevo_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[3] = fire_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[4] = keyboard_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[5] = locomotive_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[6] = person_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[7] = rose_0();
	FirstPage_ESD_Image_SlideShow_Array_Input__Property_Array[8] = seagull_0();
	object->Array_Input = FirstPage_ESD_Image_SlideShow_Array_Input__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Toggle__Initializer(FirstPage *context)
{
	Ft_Esd_Toggle *object = (Ft_Esd_Toggle *)&context->ESD_Toggle;
	Ft_Esd_Toggle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 18;
	object->Widget.LocalY = 89;
	object->Widget.LocalWidth = 123;
	object->Widget.LocalHeight = 42;
	object->Font = FirstPage_ESD_Toggle_Font__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Scrolling_Text__Initializer(FirstPage *context)
{
	Ft_Esd_ScrollingText *object = (Ft_Esd_ScrollingText *)&context->ESD_Scrolling_Text;
	Ft_Esd_ScrollingText__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = -1;
	object->Widget.LocalY = 404;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 37;
	object->Position = RIGHT_TO_LEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Push_Button__Initializer(FirstPage *context)
{
	Ft_Esd_PushButton *object = (Ft_Esd_PushButton *)&context->ESD_Push_Button;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 163;
	object->Widget.LocalY = 82;
	object->Widget.LocalWidth = 136;
	object->Widget.LocalHeight = 45;
	object->Font = FirstPage_ESD_Push_Button_Font__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Label__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_ESD_Label_Font__Property;
	object->Text = FirstPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Initializer(FirstPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = FirstPage_CLASSID;
	context->Widget.Slots = &s_FirstPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	FirstPage__Fixed_Position__Initializer(context);
	FirstPage__ESD_Image_SlideShow__Initializer(context);
	FirstPage__ESD_Toggle__Initializer(context);
	FirstPage__ESD_Scrolling_Text__Initializer(context);
	FirstPage__ESD_Push_Button__Initializer(context);
	FirstPage__ESD_Label__Initializer(context);
}

void FirstPage_End(FirstPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_SlideShow); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Toggle); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Scrolling_Text); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Push_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
}


/* end of file */
